### ISSUE TITLE
Coursera solution posted in public

### ISSUE THREAD

**Issue by cklopfenstein** [Xiaodan/Coursera-Regression-Models#1]
Hi Xiaodan - 

Maybe you didn't know this, but we are not supposed to post solutions to Coursera projects in public forums. (Technically, it violates the honor code). Some people in my class seem to have copied your solution for the Regression Models project. I'm sure that's not what you intended.

best regards, Chris Klopfenstein

**Comment by sallyblockchain** [comment]
Well, I took this course a long long time ago and since we needed to do the peer assessment, we had to put it in a public Github repo so that other students could click on the link and evaluate it. But I didn't put any project solutions to "public forums".

**Comment by cklopfenstein** [comment]
Hi -

Yeah, there is some confusion in those JHU courses on what should be posted
on GitHub, policy might have changed from when you took the course til when
I did. But I just wanted to let you know - of my 4 peer assessments for
that course (by now awhile back), 2 were more or less identical, and also
(almost) identical to your GitHub file. (Search on 'regression models
cousera', - or something - turned it up near the top of the list). But no
harm done... in the end I didn't even mark them off (since I didn't have
proof of plagiarism), but gave it to them in my comments.

best regards,

Chris Klopfenstein

**Comment by sallyblockchain** [comment]
Hi Chris,

Thanks for letting me know this issue. :( I know once the codes are public on Github for peer assessments, there will be people who will try to search for possible solutions for sure. But it's already an online course and is totally voluntary. I feel bad when people just do copy and paste only for getting the certificates.

Best,
Sally.

**Comment by philipmat** [comment]
I just want to say that your report helped me a great deal understanding the subject and while I took inspiration from it, I arrived at a different model altogether. 
And yes, I've seen a few reports that copied yours almost word for word - I guess imitation...

Anyway, thank you so very much for your pioneering effort! :+1:
